//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalShelter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.Adoption = new HashSet<Adoption>();
            this.Care_log = new HashSet<Care_log>();
            this.Medical_record = new HashSet<Medical_record>();
        }
    
        public int ID_animal { get; set; }
        public Nullable<int> Volunteer { get; set; }
        public int Species { get; set; }
        public Nullable<int> Breed { get; set; }
        public int Gender { get; set; }
        public string Nickname { get; set; }
        public string Photo { get; set; }
        public System.DateTime Date_of_birth { get; set; }
        public System.DateTime Date_of_registration { get; set; }
        public int Source_of_receipt { get; set; }
        public int Animal_status { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adoption> Adoption { get; set; }
        public virtual Animal_status Animal_status1 { get; set; }
        public virtual Breed Breed1 { get; set; }
        public virtual Gender Gender1 { get; set; }
        public virtual Source_of_receipt Source_of_receipt1 { get; set; }
        public virtual Species Species1 { get; set; }
        public virtual Volunteer Volunteer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Care_log> Care_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medical_record> Medical_record { get; set; }
        public int Age
        {
            get
            {
                var today = DateTime.Today;
                int age = today.Year - Date_of_birth.Year;
                if (Date_of_birth.Date > today.AddYears(-age)) age--;
                return age;
            }
        }
        public string AgeString
        {
            get
            {
                var today = DateTime.Today;
                int months = (today.Year - Date_of_birth.Year) * 12 + today.Month - Date_of_birth.Month;

                if (months < 12)
                {
                    return $"{months} {(months % 10 == 1 && months % 100 != 11 ? "месяц" : months % 10 >= 2 && months % 10 <= 4 && (months % 100 < 10 || months % 100 >= 20) ? "месяца" : "месяцев")}";
                }
                else
                {
                    int age = Age;
                    if (age % 10 == 1 && age % 100 != 11)
                    {
                        return $"{age} год";
                    }
                    else if (age % 10 >= 2 && age % 10 <= 4 && (age % 100 < 10 || age % 100 >= 20))
                    {
                        return $"{age} года";
                    }
                    else
                    {
                        return $"{age} лет";
                    }
                }
            }
        }
    }
}
