//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalShelter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Care_log
    {
        public int ID_care_log { get; set; }
        public System.DateTime Date_care_log { get; set; }
        public Nullable<int> Employee { get; set; }
        public Nullable<int> Volunteer { get; set; }
        public int Animal { get; set; }
        public int Care_type { get; set; }
        public int Task_status { get; set; }
        public string Comment { get; set; }
    
        public virtual Animal Animal1 { get; set; }
        public virtual Care_type Care_type1 { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Task_status Task_status1 { get; set; }
        public virtual Volunteer Volunteer1 { get; set; }
    }
}
