//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalShelter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int ID_donation { get; set; }
        public System.DateTime Date_of_donation { get; set; }
        public Nullable<int> Contractor { get; set; }
        public Nullable<int> Volunteer { get; set; }
        public int Donation_type { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Description { get; set; }
    
        public virtual Contractor Contractor1 { get; set; }
        public virtual Donation_type Donation_type1 { get; set; }
        public virtual Volunteer Volunteer1 { get; set; }
        public string Type
        {
            get
            {
                if (Volunteer1 != null)
                {
                    return "Волонтер"; // Предполагается, что у вас есть свойство LastName
                }
                else if (Contractor1 != null)
                {
                    return "Контрагент"; // Предполагается, что у вас есть свойство Name
                }
                return "Нет информации";
            }
        }
        public string PersonName
        {
            get
            {
                if (Volunteer1 != null)
                {
                    return Volunteer1.FullNameWithInitials; // Возвращаем фамилию волонтера
                }
                else if (Contractor1 != null)
                {
                    return Contractor1.Name; // Возвращаем фамилию контрагента
                }
                return "Нет информации"; // Если нет ни волонтера, ни контрагента
            }
        }
    }
}
