//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalShelter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Care_log = new HashSet<Care_log>();
            this.Veterinary_examination = new HashSet<Veterinary_examination>();
        }
    
        public int ID_employee { get; set; }
        public string Surname { get; set; }
        public string First_name { get; set; }
        public string Patronymic { get; set; }
        public int Gender { get; set; }
        public System.DateTime Date_of_birth { get; set; }
        public int Position { get; set; }
        public string Address { get; set; }
        public string Phone_number { get; set; }
        public string Email { get; set; }
        public System.DateTime Date_of_hire { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Care_log> Care_log { get; set; }
        public virtual Gender Gender1 { get; set; }
        public virtual Position Position1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Veterinary_examination> Veterinary_examination { get; set; }
        public int Age
        {
            get
            {
                var today = DateTime.Today;
                int age = today.Year - Date_of_birth.Year;
                if (Date_of_birth.Date > today.AddYears(-age)) age--;
                return age;
            }
        }
        public string AgeString
        {
            get
            {
                var today = DateTime.Today;
                int months = (today.Year - Date_of_birth.Year) * 12 + today.Month - Date_of_birth.Month;

                if (months < 12)
                {
                    return $"{months} {(months % 10 == 1 && months % 100 != 11 ? "месяц" : months % 10 >= 2 && months % 10 <= 4 && (months % 100 < 10 || months % 100 >= 20) ? "месяца" : "месяцев")}";
                }
                else
                {
                    int age = Age;
                    if (age % 10 == 1 && age % 100 != 11)
                    {
                        return $"{age} год";
                    }
                    else if (age % 10 >= 2 && age % 10 <= 4 && (age % 100 < 10 || age % 100 >= 20))
                    {
                        return $"{age} года";
                    }
                    else
                    {
                        return $"{age} лет";
                    }
                }
            }
        }
        public bool IsAllEmployees { get; set; } // Добавьте это свойство

        public string FullNameWithInitials
        {
            get
            {
                if (IsAllEmployees) return "Все"; // Возвращаем "Все" для комбобокса

                string firstInitial = !string.IsNullOrEmpty(First_name) ? First_name.Substring(0, 1) : string.Empty;
                string patronymicInitial = !string.IsNullOrEmpty(Patronymic) ? Patronymic.Substring(0, 1) : string.Empty;
                string initials = $"{firstInitial}. {patronymicInitial}.";
                return $"{Surname} {initials}".Trim();
            }
            set { }
        }
    }

}

