//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalShelter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medical_record
    {
        public int ID_medical_record { get; set; }
        public int Animal { get; set; }
        public System.DateTime Last_update_date { get; set; }
        public decimal Weight { get; set; }
        public decimal Height { get; set; }
        public string Chronic_illness { get; set; }
        public string Medical_history { get; set; }
        public string Allergy { get; set; }
        public string Vaccination { get; set; }
        public bool Sterilized { get; set; }
        public string Care_recommendation { get; set; }
    
        public virtual Animal Animal1 { get; set; }
    }
}
