//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalShelter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnimalShelterEntities : DbContext
    {
        private static AnimalShelterEntities _context;

        public AnimalShelterEntities()
            : base("name=AnimalShelterEntities")
        {
        }
        public static AnimalShelterEntities GetContext()
        {
            if (_context == null)
                _context = new AnimalShelterEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adoption> Adoption { get; set; }
        public virtual DbSet<Adoption_status> Adoption_status { get; set; }
        public virtual DbSet<Animal> Animal { get; set; }
        public virtual DbSet<Animal_status> Animal_status { get; set; }
        public virtual DbSet<Breed> Breed { get; set; }
        public virtual DbSet<Care_log> Care_log { get; set; }
        public virtual DbSet<Care_type> Care_type { get; set; }
        public virtual DbSet<Contractor> Contractor { get; set; }
        public virtual DbSet<Contractor_type> Contractor_type { get; set; }
        public virtual DbSet<Donation> Donation { get; set; }
        public virtual DbSet<Donation_type> Donation_type { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Housing_type> Housing_type { get; set; }
        public virtual DbSet<Medical_record> Medical_record { get; set; }
        public virtual DbSet<New_owner> New_owner { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Source_of_receipt> Source_of_receipt { get; set; }
        public virtual DbSet<Species> Species { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Task_status> Task_status { get; set; }
        public virtual DbSet<Veterinary_examination> Veterinary_examination { get; set; }
        public virtual DbSet<Volunteer> Volunteer { get; set; }
    }
}
