//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalShelter
{
    using System;
    using System.Collections.Generic;
    
    public partial class New_owner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public New_owner()
        {
            this.Adoption = new HashSet<Adoption>();
        }
    
        public int ID_new_owner { get; set; }
        public string Surname { get; set; }
        public string First_name { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime Date_of_birth { get; set; }
        public string Address { get; set; }
        public string Phone_number { get; set; }
        public string Email { get; set; }
        public int Housing_type { get; set; }
        public int Gender { get; set; }
        public int Contractor_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adoption> Adoption { get; set; }
        public virtual Contractor_type Contractor_type1 { get; set; }
        public virtual Gender Gender1 { get; set; }
        public virtual Housing_type Housing_type1 { get; set; }
    }
}
