//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalShelter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veterinary_examination
    {
        public int ID_veterinary_examination { get; set; }
        public System.DateTime Date_of_veterinary_examination { get; set; }
        public int Medical_record { get; set; }
        public int Veterinarian { get; set; }
        public string Conclusion { get; set; }
        public string Recommendation { get; set; }
    
        public virtual Medical_record Medical_record1 { get; set; }
    }
}
